const TEXTS = {
    descriptionEggs: "O ovo é comumente associado à galinha como sua fonte principal. No entanto, quando proveniente de outras espécies, deve-se mencionar a origem específica. O ovo é uma fonte significativa de proteínas encontradas na clara, que contém 18 aminoácidos essenciais. A gema, por sua vez, é rica em lipídios, principalmente na forma de lipoproteínas, que são altamente digeríveis para os seres humanos. Além disso, o ovo é rico em vitaminas lipossolúveis, como A, D, E, K, e hidrossolúveis, como B2 (riboflavina) e B12, além de minerais como fósforo, cálcio, ferro, sódio e potássio.",
    descriptionEggsTwo: 'A alergia ao ovo é uma das alergias mais comuns na infância, afetando de 1% a 2% das crianças, e sua prevalência ao longo da vida é de 2,5%. A principal causa da alergia está relacionada aos alérgenos presentes na clara do ovo, como ovomucoide, ovoalbumina, ovotransferrina e lisozima. A livetina é a proteína da gema mais associada à alergia ao ovo.',
    descriptionFish:"O peixe, embora seja muito importante na dieta humana, pode se transformar em um potente alergénio alimentar. Em uma criança, estabelece a terceira causa mais frequente de alergia alimentar, a seguir ao leite e ao ovo. A dominância da alergia ao peixe está ligada à sua utilização na dieta local." ,
    descriptionFishTwo: "Epidemiologicamente, é normal a alergia a peixe começar a se manifestar nos primeiros anos de vida. Contudo, os casos de início da expressão clínica em idade adulta são frequentes e valorizáveis. Habitualmente as reações alérgicas ao peixe são do tipo I, mediadas por IgE e de apresentação imediata. No entanto, o peixe pode provocar outros tipos de reações ao sistema não imunológico como intoxicações ou intolerância a algumas proteínas.",
    descriptionMilk: "O leite é conhecido como um alimento básico para crianças e um suplemento essencial na dieta de adultos, pois possui composição equilibrada de nutrientes com ótima digestibilidade, resultando em um produto com alto valor biológico. Em sua composição tem-se água, lactose, gordura, sais minerais e proteínas. Os glóbulos de gordura e as micelas de caseína tornam-se encarregados pela maior parte das características físicas (cor e estrutura) do produto.",
    descriptionMilkTwo: "Porém, sua ingestão, em alguns casos, está relacionada a reações adversas, como alergia á proteina do leite de vaca. O leite da vaca é o mais comum entre crianças, com uma incidência reportada de 2 a 5%, afetando 2 a 3% da população geral.",
    descriptionAmendoim: "Arachis hypogaea, também conhecido por Amendoim, é um decendente da família Fabaceae natural da América do Sul. Rica em óleo e proteínas, já estava presente na dieta de povos no Peru há 10.000 anos. Após a chegada dos europeus ao Continente Sul - Americano, o amendoim foi conhecido pelo mundo e hoje é a quarta oleaginosa mais cultivada, abaixo apenas da soja, algodão e canola. Sua forma de consumo é bastante diversificada e tem grande impacto econômico.",
    descriptionAmendoimTwo: "A alergia ao amendoim é uma das mais recorrentes em países como Estados Unidos e o número de casos de pacientes diagnosticados vem aumentando, afetando cerca de 1% das crianças, sensibilizadas tanto por via oral como por dermocosméticos.",
    descriptionSoja: "A soja é um alimento que contém até 48% de proteínas, porém o baixo volume de metionina limita o seu valor nutricional, o qual é abaixo ao da proteína do LV. Com o processamento da soja em farinha, acontece uma melhora da compreensão e o desmantelamento de parte dos fatores anti-nutricionais, como inibidores de enzimas digestivas. Apesar de a soja estar numa lista dos 8 alimentos mais alergênicos, os estudos apresentam que, a reação alérgica é inferior, comparando aos outros alimentos que tendem a ser mais alergênicos. Os estudos afirmam também que, a dose mínima necessária para provocar reações, aparenta ser em torno de 100 vezes maior, tornando extremamente raro o aparecimento de reações graves",
    descriptionCascaRija: "Os frutos de casca rija são alimentos considerados muito equilibrados, ocupando uma posição relevante na alimentação. São apreciados pelo seu maravilhoso sabor/aroma e pelas suas características benéficas para a saúde, esses frutos são bastante consumidos pela maioria da população mundial. Os frutos de casca rija estão positivamente ligados a hábitos de alimentação saudável, sua ingestão global praticamente dobrou nos últimos 20 anos",
    descriptionCascaRijaTwo: "Para tanto, o consumo de frutos de casca rija demonstra um risco existente para a saúde de uma pequena, mas significativa parte da população geral, no caso às pessoas que sofrem com algum tipo de restrição alimentar. O Colégio Americano para 10 as Alergias, Asma e Imunologia (ACAAI) - EUA, demonstrou que muitos pacientes com um histórico de alergia a apenas um fruto de casca rija, de árvores, são aconselhados a não consumirem outros frutos de casca rija. O conselho de não ingerir estes alergénios é baseada apenas em análises sanguíneas e teste à pele realizados, cujos resultados foram positivos.",
    descriptionGluten: "O trigo é uma das principais culturas alimentares, cultivado, consumido e comercializado em todo o mundo. A espécie de trigo comum (Triticum aestivum L.) é frequentemente usada para descrever muitas outras espécies e genótipos de trigo cultivados. O grão de trigo contém 8%–15% de proteína, dos quais 10%–15% é albumina/globulina e 85%–90% é glúten. O glúten é toda uma combinação complexa de centenas de proteínas relacionadas, mas distintas, principalmente gliadina e glutenina. Diferentes variedades de trigo variam no teor de proteína e na composição e distribuição das proteínas do glúten. Coletivamente, as proteínas gliadina e glutenina são chamadas de prolaminas, que representam proteínas de sementes insolúveis em água, mas extraíveis em etanol aquoso e são caracterizadas por altos níveis de glutamina (38%) e resíduos de prolina (20%)",


}

export default TEXTS